name: 'Sous Warp Whistle'
description: 'A recipe that contains Sous Warp Whistle configuration.'
type: 'Site'
recipes:
  - sous-paragraphs
install:
  # Core modules.
  - address
  - datetime
  - link
  - telephone
  # Contributed modules.
  - autosave_form
  - smart_date
config:
  actions:
    # Add new components to page field_content.
    field.field.node.page.field_content:
      simpleConfigUpdate:
        dependencies:
          config:
            - field.storage.node.field_content
            - node.type.page
            - paragraphs.paragraphs_type.accordion
            - paragraphs.paragraphs_type.audio
            - paragraphs.paragraphs_type.image
            - paragraphs.paragraphs_type.tabs
            - paragraphs.paragraphs_type.text
            - paragraphs.paragraphs_type.text_with_media
            - paragraphs.paragraphs_type.video
          module:
            - entity_reference_revisions  
        settings:
          handler: 'default:paragraph'
          handler_settings:
            target_bundles:
              image: image
              text: text
              text_with_media: text_with_media
              video: video
              accordion: accordion
              audio: audio
              tabs: tabs
            negate: 0
            target_bundles_drag_drop:
              accordion:
                weight: 10
                enabled: true
              accordion_item:
                weight: 11
                enabled: false
              audio:
                weight: 12
                enabled: true
              image:
                weight: 5
                enabled: true
              tab:
                weight: 14
                enabled: false
              tabs:
                weight: 15
                enabled: true
              text:
                weight: 6
                enabled: true
              text_with_media:
                weight: 7
                enabled: true
              video:
                weight: 8
                enabled: true
