name: 'Sous Warp Whistle'
description: 'A recipe that contains Sous Warp Whistle configuration.'
type: 'Site'
recipes:
  - sous-paragraphs
install:
  # Core modules
  - address
  - datetime
  - link
  - telephone
  # Contributed modules
  - smart_date
